export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const ADD_PLAYERS = 'ADD_PLAYERS';
export const ADD_PLAYERS_SUCCESS = 'ADD_PLAYERS_SUCCESS';
export const ADD_PLAYERS_FAILURE = 'ADD_PLAYERS_FAILURE';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const SAVE_GAME_SCORES = 'SAVE_GAME_SCORES';
export const FETCH_HISTORY = 'FETCH_HISTORY';
